# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78934306b38d2ee32c7d14386c843de4604cf626f798326083bcdda0e05f7e56c61d966d77ad8c7230c292781595d19f610f75f265c28b956c05b97d24cf9c02

test:
  secret_key_base: 331e37d69ca7e60a1f17b4e2659bfc90be7257e3a8747522b822d60d2d2ec29110d3aa0544498eb4ae9b3ebf42c219481060b36fa2fc307aa10e9aa97572054e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
